function sayHi () {
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi')
  console.log('hi, how are you')
}